# Generated by Django 4.1.4 on 2022-12-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
